/**
 * Staff Service - CRUD operations for staff
 */

import { supabase } from '../config/supabase.js';

/**
 * Get all unique departments from staff table
 * @returns {Promise<{data: Array|null, error: Error|null}>}
 */
export async function getUniqueDepartments() {
  const { data, error } = await supabase
    .from('staff')
    .select('department')
    .not('department', 'is', null);

  if (error) {
    return { data: null, error };
  }

  // Get unique departments
  const departments = new Set();
  if (data && data.length > 0) {
    data.forEach((staff) => {
      if (staff.department && staff.department.trim() !== '') {
        departments.add(staff.department.trim());
      }
    });
  }

  return { data: Array.from(departments).sort(), error: null };
}

/**
 * Get all staff (admin only)
 * @returns {Promise<{data: Array|null, error: Error|null}>}
 */
export async function getAllStaff(filters = {}) {
  // Extract pagination parameters (default: page=1, limit=10)
  const page = filters.page || 1;
  const limit = filters.limit || 10;
  const from = (page - 1) * limit;
  const to = from + limit - 1;

  let query = supabase
    .from('staff')
    .select('*', { count: 'exact' })
    .order('created_at', { ascending: false });

  // Apply pagination
  query = query.range(from, to);

  const { data, error, count } = await query;
  return { data, totalCount: count || 0, error };
}

/**
 * Get staff by ID
 * @param {string} staffId - Staff UUID or staff_id
 * @returns {Promise<{data: Object|null, error: Error|null}>}
 */
export async function getStaffById(staffId) {
  // Try UUID first
  let { data, error } = await supabase.from('staff').select('*').eq('id', staffId).maybeSingle();

  // If not found, try staff_id
  if (error || !data) {
    const result = await supabase.from('staff').select('*').eq('staff_id', staffId).maybeSingle();
    data = result.data;
    error = result.error;
  }

  // Handle "not found" errors gracefully
  if (error && (error.code === 'PGRST116' || error.message?.includes('0 rows'))) {
    return { data: null, error: null }; // Return null data instead of error for "not found"
  }

  return { data, error };
}

/**
 * Get staff by email
 * @param {string} email - Staff email
 * @returns {Promise<{data: Object|null, error: Error|null}>}
 */
export async function getStaffByEmail(email) {
  const { data, error } = await supabase.from('staff').select('*').eq('email', email).maybeSingle();

  // Handle "not found" errors gracefully
  if (error && (error.code === 'PGRST116' || error.message?.includes('0 rows'))) {
    return { data: null, error: null }; // Return null data instead of error for "not found"
  }

  return { data, error };
}

/**
 * Create new staff member
 * @param {Object} staffData - Staff data
 * @param {string} [staffData.staff_id] - Staff ID (optional, auto-generated if not provided)
 * @param {string} staffData.name - Full name
 * @param {string} staffData.email - Email address
 * @param {string} staffData.department - Department
 * @param {string} staffData.role - Role ('Admin' or 'Staff')
 * @param {string} password - Initial password
 * @returns {Promise<{data: Object|null, error: Error|null}>}
 */
export async function createStaff(staffData, password) {
  try {
    // Note: supabase.auth.admin.createUser() requires service role key and is server-side only
    // For client-side, we need to use a database function or edge function
    // For now, we'll use signUp API (but requires email confirmation unless disabled)

    // IMPORTANT: signUp() automatically signs in the newly created user, which logs out the admin
    // We need to save the admin's session before signUp and restore it after

    // Get current admin session before creating new user
    const {
      data: { session: adminSession },
    } = await supabase.auth.getSession();
    const adminAccessToken = adminSession?.access_token;
    const adminRefreshToken = adminSession?.refresh_token;

    // Option 1: Use signUp API (requires email confirmation unless disabled)
    // This will create the auth user and can automatically sign them in
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email: staffData.email,
      password: password,
      options: {
        emailRedirectTo: window.location.origin,
      },
    });

    if (authError) {
      // If signUp fails, try to continue without auth_user_id (can be linked later)
      // eslint-disable-next-line no-console
      console.warn(
        'Failed to create auth user, creating staff record without auth_user_id:',
        authError
      );

      // Create staff record without auth_user_id (can be linked later via migration 008)
      // staff_id will be auto-generated by database trigger if not provided
      const insertData = {
        auth_user_id: null, // Will be linked later
        name: staffData.name,
        email: staffData.email,
        department: staffData.department,
        role: staffData.role || 'Staff',
        status: 'active',
      };

      // Only include staff_id if provided (otherwise trigger will generate it)
      if (staffData.staff_id && staffData.staff_id.trim() !== '') {
        insertData.staff_id = staffData.staff_id;
      }

      const { data, error } = await supabase
        .from('staff')
        .insert(insertData)
        .select()
        .maybeSingle();

      if (error) {
        return { data: null, error };
      }

      // If auth user was created, try to link it
      if (authData?.user?.id) {
        // Update staff record with auth_user_id
        await supabase.from('staff').update({ auth_user_id: authData.user.id }).eq('id', data.id);

        return { data: { ...data, auth_user_id: authData.user.id }, error: null };
      }

      return { data, error: null };
    }

    // Auth user created successfully, now create staff record
    // staff_id will be auto-generated by database trigger if not provided
    const insertData = {
      auth_user_id: authData.user.id, // Link to auth user
      name: staffData.name,
      email: staffData.email,
      department: staffData.department,
      role: staffData.role || 'Staff',
      status: 'active',
    };

    // Only include staff_id if provided (otherwise trigger will generate it)
    if (staffData.staff_id && staffData.staff_id.trim() !== '') {
      insertData.staff_id = staffData.staff_id;
    }

    const { data, error } = await supabase.from('staff').insert(insertData).select().maybeSingle();

    if (error) {
      // If staff creation fails but auth user was created, we have an orphaned auth user
      // This is a problem, but we'll return the error
      return { data: null, error };
    }

    // IMPORTANT: signUp() automatically signs in the newly created user, which logs out the admin
    // We need to restore the admin's session
    // First, sign out the newly created user
    try {
      await supabase.auth.signOut();
    } catch (signOutErr) {
      // eslint-disable-next-line no-console
      console.warn('Error signing out newly created user (non-critical):', signOutErr);
    }

    // Restore admin session if we saved the tokens
    if (adminAccessToken && adminRefreshToken) {
      try {
        // Restore the admin's session using setSession
        const { error: sessionError } = await supabase.auth.setSession({
          access_token: adminAccessToken,
          refresh_token: adminRefreshToken,
        });

        if (sessionError) {
          // eslint-disable-next-line no-console
          console.warn('Failed to restore admin session (non-critical):', sessionError);
          // Admin may need to refresh the page or sign in again
        } else {
          // eslint-disable-next-line no-console
          console.log('Admin session restored successfully');
        }
      } catch (sessionErr) {
        // eslint-disable-next-line no-console
        console.warn('Error restoring admin session (non-critical):', sessionErr);
        // Admin may need to refresh the page or sign in again
      }
    }

    return { data, error: null };
  } catch (error) {
    return { data: null, error };
  }
}

/**
 * Update staff member
 * @param {string} staffId - Staff UUID
 * @param {Object} updates - Fields to update
 * @returns {Promise<{data: Object|null, error: Error|null}>}
 */
export async function updateStaff(staffId, updates) {
  try {
    // eslint-disable-next-line no-console
    console.log('Updating staff:', { staffId, updates });

    const { data, error } = await supabase
      .from('staff')
      .update(updates)
      .eq('id', staffId)
      .select()
      .maybeSingle();

    // Handle "not found" errors gracefully
    if (error && (error.code === 'PGRST116' || error.message?.includes('0 rows'))) {
      return { data: null, error: new Error('Staff member not found') };
    }

    if (error) {
      // eslint-disable-next-line no-console
      console.error('Update staff error:', {
        code: error.code,
        message: error.message,
        details: error.details,
        hint: error.hint,
      });
    } else {
      // eslint-disable-next-line no-console
      console.log('Staff updated successfully:', data);
    }

    return { data, error };
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error('Exception in updateStaff:', error);
    return { data: null, error };
  }
}

/**
 * Deactivate staff member
 * @param {string} staffId - Staff UUID
 * @returns {Promise<{data: Object|null, error: Error|null}>}
 */
export async function deactivateStaff(staffId) {
  return updateStaff(staffId, { status: 'inactive' });
}

/**
 * Activate staff member
 * @param {string} staffId - Staff UUID
 * @returns {Promise<{data: Object|null, error: Error|null}>}
 */
export async function activateStaff(staffId) {
  return updateStaff(staffId, { status: 'active' });
}

/**
 * Search staff
 * @param {string} searchTerm - Search term for name, staff_id, or department
 * @returns {Promise<{data: Array|null, error: Error|null}>}
 */
export async function searchStaff(searchTerm) {
  const { data, error } = await supabase
    .from('staff')
    .select('*')
    .or(
      `name.ilike.%${searchTerm}%,staff_id.ilike.%${searchTerm}%,department.ilike.%${searchTerm}%`
    )
    .order('name', { ascending: true });

  return { data, error };
}

/**
 * Reset staff password (admin function)
 * @param {string} email - Staff email
 * @param {string} newPassword - New password
 * @returns {Promise<{error: Error|null}>}
 */
export async function resetStaffPassword(email, newPassword) {
  const { error } = await supabase.auth.admin.updateUserByEmail(email, {
    password: newPassword,
  });
  return { error };
}
